// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Drink", b =>
                {
                    b.Property<int>("DrinkType")
                        .HasColumnType("int");

                    b.Property<string>("DrinkName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DrinkImageURI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail2")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DrinkType", "DrinkName");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail1");

                    b.HasIndex("UserEmail2");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("Model.Location", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("City", "Street", "Zipcode", "Number", "Suffix");

                    b.HasIndex("UserEmail");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Model.Match", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("Model.Message", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Matchid")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Text", "TimeSent");

                    b.HasIndex("Matchid");

                    b.HasIndex("SenderEmail");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Matchid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfielImageURI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Email");

                    b.HasIndex("Matchid");

                    b.HasIndex("UserEmail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.Drink", b =>
                {
                    b.HasOne("Model.User", null)
                        .WithMany("Dislikes")
                        .HasForeignKey("UserEmail");

                    b.HasOne("Model.User", null)
                        .WithMany("Favourites")
                        .HasForeignKey("UserEmail1");

                    b.HasOne("Model.User", null)
                        .WithMany("Likes")
                        .HasForeignKey("UserEmail2");
                });

            modelBuilder.Entity("Model.Location", b =>
                {
                    b.HasOne("Model.User", null)
                        .WithMany("Cities")
                        .HasForeignKey("UserEmail");
                });

            modelBuilder.Entity("Model.Message", b =>
                {
                    b.HasOne("Model.Match", null)
                        .WithMany("Chat")
                        .HasForeignKey("Matchid");

                    b.HasOne("Model.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderEmail");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.HasOne("Model.Match", null)
                        .WithMany("Users")
                        .HasForeignKey("Matchid");

                    b.HasOne("Model.User", null)
                        .WithMany("Matches")
                        .HasForeignKey("UserEmail");
                });

            modelBuilder.Entity("Model.Match", b =>
                {
                    b.Navigation("Chat");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Dislikes");

                    b.Navigation("Favourites");

                    b.Navigation("Likes");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
